version: '3.8'

services:
  mysql:
    build: .
    container_name: mi_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mi_base_de_datos
      MYSQL_USER: mi_usuario
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"  # Exponer puerto 3306 para conexiones externas
    volumes:
      - ./data:/var/lib/mysql  # Persistencia de datos
    command: --bind-address=0.0.0.0 --default-authentication-plugin=mysql_native_password  # Aquí agregamos las opciones
    networks:
      - backend-network
    restart: always

networks:
  backend-network:
    driver: bridge
